name: Python CI CD

on:
  push:
    branches:
      - dev
      - main
jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup python
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install dependencies
      - run: pip install -r requirements.txt

      - name: Run test
      - uses: pytest
