name: Python CI CD

on:
  push:
    branches:
      - dev
      - main
jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run test
        run: pytest

  deploy-dev:
    if: github.ref == 'refs/heads/dev'
    needs: test
    runs-on: ubuntu-latest

    steps:
      - name: Execute script on EC2
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.DEV_HOST }}
          username: ubuntu
          key: ${{ secrets.DEV_SSH_KEY }}
          script: |
            cd /home/ubuntu
            if [ -d "simple_python_app" ]; then
              rm -rf simple_python_app
            fi

            git clone -b dev https://${{ secrets.GH_TOKEN }}@github.com/workemail-devops/simple_python_app.git

            cd simple_python_app

            chmod +x deploy.sh
            bash deploy.sh
